#!/usr/bin/env node
/**
 * ============================================================================
 * Snapshot the approved Pledge Wall entries into data/pledges.js
 * ============================================================================
 * pledge-wall.html used to have nothing to show until Google Apps Script
 * answered — a few seconds on a cold start, and an empty wall until then. This
 * bakes the approved list into a static file the page ships with, so the real
 * wall is on screen in the first paint with no network round trip at all. The
 * page still fetches the live list and upgrades itself, so a pledge approved
 * since the last build appears a moment later.
 *
 * Run by .github/workflows/daily-update.yml alongside the data pipeline.
 * Deliberately fails soft: a wobbly Apps Script must not break the build or
 * blank the wall, so on any error the existing snapshot is left exactly as is.
 * ----------------------------------------------------------------------------
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'data', 'pledges.js');
const SHARED = path.join(ROOT, 'functions', '_shared.js');
const TIMEOUT_MS = 30000;
const ATTEMPTS = 3;

// Single source of truth for the endpoint — read it rather than duplicating it.
function wallUrl() {
  const src = fs.readFileSync(SHARED, 'utf8');
  const m = /WALL_APPS_SCRIPT_URL\s*=\s*'([^']+)'/.exec(src);
  if (!m) throw new Error('WALL_APPS_SCRIPT_URL not found in functions/_shared.js');
  if (m[1].indexOf('REPLACE_WITH') === 0) throw new Error('WALL_APPS_SCRIPT_URL is still a placeholder');
  return m[1] + '?action=pledges&_=' + Date.now();
}

// Only the fields the wall renders. Nothing else belongs in a public file —
// and a smaller payload is the point of the exercise.
function publicRow(p) {
  return {
    id: String(p.id || ''),
    createdAt: String(p.createdAt || ''),
    publishedAt: String(p.publishedAt || ''),
    name: String(p.name || ''),
    location: String(p.location || ''),
    barrier: String(p.barrier || ''),
    why: String(p.why || ''),
    photoId: String(p.photoId || '')
  };
}

// One bad response used to cost the wall a whole day: a single 404 from Apps
// Script on 2026-08-13 kept a snapshot from the previous morning, so a pledge
// approved in between was missing from the first paint until the next build.
// The failures are transient — cold starts and the occasional 404 on the /exec
// redirect — so retry before giving up on the day.
async function fetchPledges() {
  let lastErr;
  for (let attempt = 1; attempt <= ATTEMPTS; attempt++) {
    try {
      const res = await fetch(wallUrl(), {
        headers: { accept: 'application/json' },
        signal: AbortSignal.timeout(TIMEOUT_MS)
      });
      if (!res.ok) throw new Error('HTTP ' + res.status);
      return await res.json();
    } catch (err) {
      lastErr = err;
      if (attempt < ATTEMPTS) {
        console.warn('  attempt ' + attempt + ' failed (' + err.message + ') — retrying');
        await new Promise((r) => setTimeout(r, attempt * 5000));
      }
    }
  }
  throw lastErr;
}

async function main() {
  const data = await fetchPledges();
  if (!data || data.result !== 'success' || !Array.isArray(data.pledges)) {
    throw new Error('unexpected payload: ' + JSON.stringify(data).slice(0, 200));
  }

  const rows = data.pledges
    .filter((p) => p && p.id && p.barrier)
    .map(publicRow);

  // An empty list is almost certainly a backend hiccup rather than an empty
  // wall, and overwriting a good snapshot with nothing is the one outcome worse
  // than a stale snapshot.
  if (!rows.length) throw new Error('backend returned zero pledges — keeping the previous snapshot');

  const body = '// Generated by scripts/snapshot-pledges.js — do not edit by hand.\n'
    + '// The Pledge Wall paints from this instantly, then upgrades from /api/wall.\n'
    + 'window.__PLEDGE_SNAPSHOT = ' + JSON.stringify({ t: new Date().toISOString(), rows: rows }) + ';\n';

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log('Wrote ' + path.relative(ROOT, OUT) + ' — ' + rows.length + ' pledges, '
    + Math.round(body.length / 1024) + ' KB');
}

main().catch((err) => {
  const kept = fs.existsSync(OUT) ? 'existing snapshot kept' : 'no snapshot yet — wall falls back to its seed pledges';
  console.warn('::warning::Pledge snapshot skipped (' + err.message + ') — ' + kept);
  process.exit(0); // never fail the build over this
});
