#!/usr/bin/env node
/**
 * ============================================================================
 * Snapshot the published Ambassador Notes into data/posts.js
 * ============================================================================
 * posts.html had nothing to show until Google Apps Script answered, and no
 * fallback if it didn't: a cold backend meant an empty page, then "Could not
 * load posts". This bakes the published list into a static file the page ships
 * with, so the notes are on screen in the first paint with no round trip. The
 * page still fetches the live list and upgrades itself, so a note published
 * since the last build appears a moment later.
 *
 * Run by .github/workflows/daily-update.yml. Sibling of snapshot-pledges.js and
 * deliberately fails soft for the same reason: a wobbly backend must not break
 * the build or blank the page, so on any error the existing snapshot stands.
 * ----------------------------------------------------------------------------
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'data', 'posts.js');
const SHARED = path.join(ROOT, 'functions', '_shared.js');
// This backend is the slow one — a cold Apps Script here has been measured well
// past 30s, which is the whole reason the page can't wait on it at runtime. A
// build step can afford to be patient, and to try again.
const TIMEOUT_MS = 60000;
const ATTEMPTS = 3;

// Single source of truth for the endpoint — read it rather than duplicating it.
function postsUrl() {
  const src = fs.readFileSync(SHARED, 'utf8');
  const m = /^export const APPS_SCRIPT_URL\s*=\s*'([^']+)'/m.exec(src);
  if (!m) throw new Error('APPS_SCRIPT_URL not found in functions/_shared.js');
  if (m[1].indexOf('REPLACE_WITH') === 0) throw new Error('APPS_SCRIPT_URL is still a placeholder');
  return m[1] + '?action=published&_=' + Date.now();
}

// Only the fields the index cards render — the body lives behind /post.
function publicRow(p) {
  return {
    id: String(p.id || ''),
    title: String(p.title || ''),
    dek: String(p.dek || ''),
    category: String(p.category || ''),
    tags: Array.isArray(p.tags) ? p.tags.map(String).slice(0, 8) : [],
    authorName: String(p.authorName || ''),
    ambassadorSlug: String(p.ambassadorSlug || ''),
    cover: String(p.cover || ''),
    publishedAt: String(p.publishedAt || ''),
    createdAt: String(p.createdAt || '')
  };
}

async function fetchPublished() {
  let lastErr;
  for (let attempt = 1; attempt <= ATTEMPTS; attempt++) {
    try {
      const res = await fetch(postsUrl(), {
        headers: { accept: 'application/json' },
        signal: AbortSignal.timeout(TIMEOUT_MS)
      });
      if (!res.ok) throw new Error('HTTP ' + res.status);
      return await res.json();
    } catch (err) {
      lastErr = err;
      // The first request is usually the one that pays the cold start; a second
      // attempt a few seconds later normally lands quickly.
      if (attempt < ATTEMPTS) {
        console.warn('  attempt ' + attempt + ' failed (' + err.message + ') — retrying');
        await new Promise((r) => setTimeout(r, attempt * 5000));
      }
    }
  }
  throw lastErr;
}

async function main() {
  const data = await fetchPublished();
  if (!data || data.result !== 'success' || !Array.isArray(data.posts)) {
    throw new Error('unexpected payload: ' + JSON.stringify(data).slice(0, 200));
  }

  const rows = data.posts.filter((p) => p && p.id).map(publicRow);

  // An empty list is far more likely a backend hiccup than a site with no
  // notes, and replacing a good snapshot with nothing is the worst outcome.
  if (!rows.length) throw new Error('backend returned zero posts — keeping the previous snapshot');

  const body = '// Generated by scripts/snapshot-posts.js — do not edit by hand.\n'
    + '// Ambassador Notes paints from this instantly, then upgrades from /api/posts.\n'
    + 'window.__POSTS_SNAPSHOT = ' + JSON.stringify({ t: new Date().toISOString(), rows: rows }) + ';\n';

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log('Wrote ' + path.relative(ROOT, OUT) + ' — ' + rows.length + ' posts, '
    + Math.round(body.length / 1024) + ' KB');
}

main().catch((err) => {
  const kept = fs.existsSync(OUT) ? 'existing snapshot kept' : 'no snapshot yet — page falls back to the live fetch';
  console.warn('::warning::Posts snapshot skipped (' + err.message + ') — ' + kept);
  process.exit(0); // never fail the build over this
});
